# 端口号
server:
  port: 7101
# 服务注册相关配置
eureka:
  # 服务实例主机名
  instance:
    hostname: localhost
  # 服务提供者配置
  client:
    # registerWithEureka=false表示当前服务注册中心不在其他服务注册中心进行注册（当服务注册中心是单点而非高可用时的配置方式）
    # fetchRegistry=false表示当前服务注册中心不获取其他服务注册中心的注册信息（当服务注册中心是单点而非高可用时的配置方式）
    # 这两个配置，只有在当服务注册中心是单点配置时必然为false。
    registerWithEureka: false
    fetchRegistry: false
    # 注册中心地址，即http://localhost:7101/eureka
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
