server:
  port: 7301
spring:
  profiles: cons1
  main:
    allow-bean-definition-overriding: true
  application:
    name: eureka-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/,http://peer2:7102/eureka/,http://peer3:7103/eureka/
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000

---
server:
  port: 7302
spring:
  profiles: cons2
  main:
    allow-bean-definition-overriding: true
  application:
    name: eureka-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/,http://peer2:7102/eureka/,http://peer3:7103/eureka/
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000