server:
  port: 7301
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: eureka-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000